name: flutter_app_template
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Logger
  simple_logger: ^1.10.0

  # LocalDatabase
  shared_preferences: ^2.5.3

  # Riverpod
  hooks_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Hooks
  flutter_hooks: ^0.21.3

  # Entity
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  equatable:

  # Dialog
  adaptive_dialog:

  # Access local storage
  path_provider:

  # Date
  intl:

  # Reactive
  rxdart:

  # Data share
  share_plus:

  # WebView
  flutter_inappwebview: ^6.1.5

  # Launcher
  url_launcher:
  map_launcher:

  # Transition
  page_transition:

  # Image
  image_picker:
  image_gallery_saver_plus: ^4.0.1
  image_cropper: ^11.0.0
  flutter_image_compress:
  extended_image:
  flutter_svg:

  # Picker
  numberpicker:

  # Permission
  permission_handler:

  # Firebase
  firebase_core: ^4.1.1
  firebase_analytics: ^12.0.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  cloud_functions: ^6.0.2
  firebase_messaging: ^16.0.2
  firebase_crashlytics: ^5.0.2
  firebase_remote_config: ^6.0.2

  # LocalNotification
  flutter_local_notifications:
  flutter_timezone:
  timezone:

  # Api
  retrofit:
  dio:

  # Navigation
  go_router:

  # Info
  package_info_plus:
  device_info_plus:

  # Text
  flutter_linkify:

  # Widget
  flutter_slidable:
  dismissible_page:

  # Other
  uuid:
  synchronized:
  hashids2:
  collection:
  quiver:

dev_dependencies:
  # Test
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1

  # Static analysis
  pedantic_mono: ^1.34.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

  # Serializer
  json_serializable: ^6.11.1

  # Code generator
  build_runner: ^2.9.0
  freezed: ^3.2.3
  flutter_gen_runner: ^5.12.0
  retrofit_generator: ^10.0.6
  riverpod_generator: ^3.0.3

  # Other
  flutter_launcher_icons:

dependency_overrides:
  test: ^1.26.3
  test_api: ^0.7.7

flutter_gen:
  output: lib/core/res/gen/
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # カスタムフォントを利用する場合はここを設定する
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
# flutter_launcher_iconsを利用してアイコンのリサイズする場合はここを設定する
#flutter_icons:
#  android: true
#  ios: true
#  image_path_android: "assets/icon/icon_android.png"
#  image_path_ios: "assets/icon/icon_ios.png"
#  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"
#  adaptive_icon_background: "#F4A281"

