name: flutter_app_template
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # LocalDatabase
  shared_preferences: ^2.5.3

  # Riverpod
  hooks_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Hooks
  flutter_hooks: ^0.21.3

  # Api
  retrofit:
  dio:

  # Entity
  freezed_annotation: ^3.1.0

  # Launcher
  url_launcher: ^6.3.2

  # Image
  extended_image: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mockito: ^5.5.1

  # Static analysis
  pedantic_mono: ^1.34.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

  # Serializer
  json_serializable: ^6.11.1

  # Code generator
  build_runner: ^2.9.0
  freezed: ^3.2.3
  riverpod_generator: ^3.0.3
  retrofit_generator: ^10.0.6

dependency_overrides:
  test: ^1.26.3
  test_api: ^0.7.7

flutter:
  uses-material-design: true
